# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
baud: 57600
timeout: 0.5

rate: 50    #rate of outside ROS loop; should be at least sensorstate_rate
sensorstate_rate: 2

use_base_controller: True
base_controller_rate: 10

base_frame: base_link

# === Robot drivetrain parameters
wheel_diameter: 0.075 
wheel_diameter_left: 0.075 
wheel_diameter_right: 0.075 
wheel_track: 0.2465 #grey wheels corrected after angular calibration; change this parameter by dividing it by your correction factor.

encoder_resolution: 6400 # From Pololu for 100:1 motors
gear_reduction: 1 
motors_reversed: False

# === PID parameters
Kp: 1
Kd: 0
Ki: 30
Ko: 5
accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)

sensors: {
  motor_current_left:   {pin: 14, type: PololuMotorCurrent, rate: 2},
  motor_current_right:  {pin: 15, type: PololuMotorCurrent, rate: 2},
#  sonar_front_left:   {pin: 0, type: LaserScanPing, rate: 2, frame_id: /base_fl_sonar_link},
#  sonar_front_center:   {pin: 1, type: LaserScanPing, rate: 2, frame_id: /base_fc_sonar_link},
#  sonar_front_right:   {pin: 2, type: LaserScanPing, rate: 2, frame_id: /base_fr_sonar_link},
#
#  sonar_front_left:   {pin: 100, type: Ping, rate: 2, frame_id: /base_fl_sonar_link},
#  sonar_front_center:   {pin: 100, type: Ping, rate: 2, frame_id: /base_fc_sonar_link},
#  sonar_front_right:   {pin: 100, type: Ping, rate: 2, frame_id: /base_fr_sonar_link},
}